### ISSUE TITLE
NPE when using some shared secrets

### ISSUE THREAD

**Issue by mostrovoi** [funcool/buddy-auth#48]
I have tried to use jws_backend function and sometimes works fine but for some shared secrets does not seem to work. I wonder if has to do with the length of the shared secret or some lengths cannot be used? This is the full stacktrace when a request is made to the backend and tries to unsign the shared secret contained in the token:

java.lang.NullPointerException: null
    at clojure.string$replace.invokeStatic(string.clj:101)
    at clojure.string$replace.invoke(string.clj:75)
    at buddy.core.codecs$safebase64__GT_bytes.invokeStatic(codecs.clj:116)
    at buddy.core.codecs$safebase64__GT_bytes.invoke(codecs.clj:109)
    at buddy.sign.jws$unsign.invokeStatic(jws.clj:176)
    at buddy.sign.jws$unsign.invoke(jws.clj:168)
    at buddy.auth.backends.token$jws_backend$reify__15853._authenticate(token.clj:53)
    at buddy.auth.middleware$wrap_authentication$fn__15974$fn__15978.invoke(middleware.clj:36)
    at buddy.auth.middleware$wrap_authentication$fn__15974.invoke(middleware.clj:31)
    at compojure.core$routing$fn__10214.invoke(core.clj:144)

I am using version 0.9.0

**Comment by niwinz** [comment]
Please, can you provide a reproducible test case for that?

**Comment by mostrovoi** [comment]
Sure 2 different calls:

curl -i  -H "Authorization: Bearer eyJhbGciOifdsJIUzI1NiIsInR5cCI6IkpXUyJ9.VCzc1U" -H "Content-Type: application/json" -X POST -d '{}' http://avoptest.csc.fi/api/public/luovastaajatunnus

This works. I get 403 as expected.

The second one (tampered) does not and throws the above aforementioned stacktrace:

curl -i  -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXUyJ9.VCzc1U" -H "Content-Type: application/json" -X POST -d '{}' http://avoptest.csc.fi/api/public/luovastaajatunnus

**Comment by mostrovoi** [comment]
and this is our code snippet using your library:

https://github.com/CSC-IT-Center-for-Science/arvo/blob/master/aipal/src/clj/aipal/rest_api/avopvastaajatunnus.clj#L56

**Comment by niwinz** [comment]
Thanks.

**Comment by niwinz** [comment]
Some NPE exception is fixed and new release is issued (0.13.0), the exactly yours NPE I can't reproduce on 0.12.0 so perhaps it is already fixed.
